default: &default
  secret_key_base: "<%= Rails.application.credentials.secret_key_base %>"
  mailer_sender: "support@somleng.org"
  aws_sqs_default_queue_name: <%= ENV.fetch("AWS_SQS_DEFAULT_QUEUE_NAME", "default") %>
  aws_sqs_scheduler_queue_name: <%= ENV.fetch("AWS_SQS_SCHEDULER_QUEUE_NAME", "scheduler") %>
  aws_region: <%= ENV.fetch("AWS_DEFAULT_REGION", "ap-southeast-1") %>
  uploads_bucket: <%= ENV.fetch("UPLOADS_BUCKET", "uploads.somleng.org") %>
  default_sip_gateway:
    enabled: true
    host: "<%= Rails.application.credentials.default_sip_gateway_host %>"
    caller_id: "<%= Rails.application.credentials.default_sip_gateway_caller_id %>"
    prefix: "+"

production: &production
  <<: *default
  default_url_host: "https://scfm.somleng.org"
  smtp_username: <%= ENV["SMTP_USERNAME"] %>
  smtp_password: <%= ENV["SMTP_PASSWORD"] %>
  smtp_address: "email-smtp.us-east-1.amazonaws.com"
  sentry_dsn: "<%= Rails.application.credentials.sentry_dsn %>"
  internal_api_http_auth_user: <%= ENV["INTERNAL_API_HTTP_AUTH_USER"] %>
  internal_api_http_auth_password: <%= ENV["INTERNAL_API_HTTP_AUTH_PASSWORD"] %>

development: &development
  <<: *default
  default_url_host: "http://localhost:3000"

test:
  <<: *development
  default_url_host: https://twilreapi.somleng.org
