queues:
  - [<%= ENV.fetch("AWS_SQS_SCHEDULER_QUEUE_NAME", "scheduler") %>, 1]
  - [<%= ENV.fetch("AWS_SQS_HIGH_PRIORITY_QUEUE_NAME", "high_priority") %>, 5]
  - [<%= ENV.fetch("AWS_SQS_DEFAULT_QUEUE_NAME", "default") %>, 10]
